import type { Metadata } from "next";
import "./globals.css";
import { SideBar } from "../components/SideBar/Index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="pt-BR" className="h-full">
      <body className="flex h-screen overflow-hidden">
        <SideBar></SideBar>
        <main className="flex-1 overflow-y-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
